version: '3.8'

services:
  fault-analysis:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - FAULT_WORKING_DIR=/app/fault_analysis_rag
      - LOG_LEVEL=INFO
    volumes:
      - ./input_excel_files:/app/input_excel_files
      - ./fault_analysis_rag:/app/fault_analysis_rag
      - ./logs:/app/logs
    restart: unless-stopped